repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest stable version of Black
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the latest stable version of Flake8
    hooks:
      - id: flake8
        args: [--max-line-length=88]  # Optional: Customize Flake8 arguments
        additional_dependencies: []   # Optional: Add Flake8 plugins if needed

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.5.1  # Use the latest stable version of Mypy
  #   hooks:
  #     - id: mypy
  #       args:
  #         - --ignore-missing-imports
  #         - --explicit-package-bases
  #       additional_dependencies: []       # Optional: Add Mypy plugins if needed
